### ISSUE TITLE
Add support for both ES modules and Common JS

### ISSUE THREAD

**Issue by Yang-33** [line/line-bot-sdk-nodejs#758]
### Summary
As the JavaScript ecosystem continues to evolve, ES Modules (ESM) have become a standard for modern development, offering benefits such as improved loading performance and better tooling support. To align with these advancements and increase the library's usability across various environments, I propose adding support for ES Modules.

### Motivation
Adding ESM support would make `line/line-bot-sdk-nodejs` more versatile and accessible for developers working in both Node.js and compatible environments. It would also facilitate smoother integration with modern build tools and enable tree-shaking for more efficient bundling.

**Comment by Yang-33** [comment]
## Task lists

- [ ] https://github.com/line/line-bot-sdk-nodejs/pull/792
- [ ] https://github.com/line/line-bot-sdk-nodejs/pull/793
- [ ] https://github.com/line/line-bot-sdk-nodejs/pull/794
- [ ] https://github.com/line/line-bot-sdk-nodejs/pull/795
- [ ] https://github.com/line/line-bot-sdk-nodejs/pull/797
- [ ] (WIP) compatibility issue for Typescript < 5.3
- [ ] (WIP) document

**Comment by Yang-33** [comment]
These changes are in [v9.1.0](https://github.com/line/line-bot-sdk-nodejs/releases/tag/v9.1.0)!
